### ISSUE TITLE
Weird rubby cli return when using set

### ISSUE THREAD

**Issue by laradji** [Pragmatic-Source/zabby#4]
Zabby(Zabby::Runner) > set user "Nacer"
 => nil 
Zabby(Zabby::Runner) > 

Zabby(Zabby::Runner) > set password "UbberPassword"
 => "UbberPassword" 
Zabby(Zabby::Runner) > 

result :

Zabby(Zabby::Runner) > login
Zabby::AuthenticationError: Code: [-32602]. Message: [Invalid params.]. Data: [Login name or password is incorrect].
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/zabby-0.0.4/lib/zabby/connection.rb:122:in `query_zabbix_rpc'
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/zabby-0.0.4/lib/zabby/connection.rb:54:in`authenticate'
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/zabby-0.0.4/lib/zabby/connection.rb:34:in `login'
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/zabby-0.0.4/lib/zabby/runner.rb:110:in`login'
    from (irb#1):11
Zabby(Zabby::Runner) >

PS : i use zabbix 1.9.6

**Comment by Farzy** [comment]
Please try:

```
set :user => "User"
set :password => "S3cret"
```

Oh and by the way `zabbyrb` is less reliable than `zabbysh` as it uses the full bloated **IRB** library :) "`user`" must be defined somewhere in IRB.

If it works with `zabbysh`I may have a method name collision with "user". In this case I may suppress my fancy "set xxx" code.

**Comment by laradji** [comment]
bettrer :

Zabby(Zabby::Runner) > login
 => "4225bf2600000000009e2c0d61786e"

**Comment by Farzy** [comment]
The "**set user 'xxx'**" syntax has been suppressed in v0.1.0, now the only valid syntax is "**set :user => 'xxx'**".
